### ISSUE TITLE
Ferm --interactive : ferm interactive mode not possible: /dev/stderr is not a tty

### ISSUE THREAD

**Issue by trompx** [cxcv/ferm#3]
Hello,

I have a ansible ferm role. When I apply iptables, I use interactive mode to prevent getting locked out by accident :
```
- name: Apply iptables rules if ferm is enabled
  command: ferm --interactive --slow /etc/ferm/ferm.conf
```

However, I get the following error :
```
stderr: ferm interactive mode not possible: /dev/stderr is not a tty
```

In fact, interactive mode need a tty so the user can confirm he wants to keep the config within the default 30s.

Would it be possible to have an option to force the ferm rules to drop after X seconds without prompting user input ?

Thanks

**Comment by trompx** [comment]
As a workaround, I run ferm without interactive mode and add a job that stops ferm after 1 minute.
```
echo /etc/init.d/ferm stop | at now +1min
```

**Comment by cxcv** [comment]
Hi, this is not the master repository, please report at
http://ferm.foo-projects.org/
