### ISSUE TITLE
"hashlimit-above" or "! hashlimit not possible"

### ISSUE THREAD

**Issue by jpiccaluga** [cxcv/ferm#4]
Hello,

I found that it's not possible to hashlimit-above or negated hashlimit with ferm. Is it possible to activate this option?

Best Regards,

Julien Piccaluga

**Comment by cxcv** [comment]
Hi Julien,

please report upstream at http://ferm.foo-projects.org/


Greetings
Benjamin

**Comment by bechtoldt** [comment]
@cxcv why don't add a remark to the repo descr to state that it's a clone/fork? :)
